# Generated by Django 3.2.8 on 2021-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_phone',
            field=models.CharField(default='DEFAULT VALUE', max_length=200),
        ),
    ]
